AllCops:
  TargetRubyVersion: 2.4.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - tmp/**/*
    - bin/*
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - Gemfile
    - Guardfile
    - Rakefile

Rails:
  Enabled: true

Metrics/LineLength:
  Exclude:
    - "config/**/*"

Metrics/BlockLength:
  Exclude:
    - "config/environments/**/*"

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrivialAccessors:
  AllowPredicates: true

Style/SpaceBeforeFirstArg:
  Enabled: false
