AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - tmp/**/*
    - bin/*
    - Capfile
    - config.ru
    - config/boot.rb
    - config/environment.rb
    - config/application.rb
    - config/puma.rb
    - config/spring.rb
    - config/initializers/*
    - config/environments/*
    - db/schema.rb
    - Gemfile
    - Guardfile
    - Rakefile
    - db/migrate/**/*

Rails:
  Enabled: true

Metrics/LineLength:
  Exclude:
    - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/environments/**/*
    - config/**/*
    - spec/**/*.rb

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/TrivialAccessors:
  AllowPredicates: true

Layout/SpaceBeforeFirstArg:
  Enabled: false
